# Project information
site_name: Рисале-и Нур‎ 
site_author: Yryskul Turduev
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project – customizable,
  searchable, mobile-friendly, 40+ languages

extra:
  generator: false

# Configuration
theme:
  name: material

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: ru
  features:
    - navigation.top
    #- navigation.instant
    #- navigation.sections
    #- navigation.tabs
  palette:
    - scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: imgs/rnk_logo.png
  favicon: imgs/rnk_logo.png

extra_css:
  - stylesheets/styles.css

extra_javascript:
  - javascripts/main.js

# Plugins
plugins:
  - search

# Page tree
nav:
  - Аса-йы Муса:
    - Аса-йы Муса: books/asay_musa/main.md
    - Биринчи маселе: books/asay_musa/1_mesele.md
    - Экинчи маселе: books/asay_musa/2_mesele.md
    - Үчүнчү маселе: books/asay_musa/3_mesele.md
    - Төртүнчү маселе: books/asay_musa/4_mesele.md
    - Бешинчи маселе: books/asay_musa/5_mesele.md
    - Алтынчы маселе: books/asay_musa/6_mesele.md
  - Кастамону лахикасы:
    - Кастамону лахикасы: books/kastamon/main.md
    - Унутчаактык: books/kastamon/content1.md
  - Лемалар:
    - Биринчи лема: books/lemalar/1_lema.md
    - Он Жетинчи лема: books/lemalar/17_lema.md
    - Жыйырманчы лема: books/lemalar/20_lema.md
    - Жыйырма биринчи лема: books/lemalar/21_lema.md
    - Жыйырма бешинчи лема: books/lemalar/25_lema.md