# Project information
site_name: Рисале-и Нур‎ 
site_author: Yryskul Turduev
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project – customizable,
  searchable, mobile-friendly, 40+ languages

extra:
  generator: false

# Configuration
theme:
  name: material

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: ru
  features:
    - navigation.top
    #- navigation.instant
    #- navigation.sections
    #- navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search

# Page tree
nav:
  - Аса-йы Муса:
    - Аса-йы Муса: books/asay_musa/main.md
    - 1-маселе: books/asay_musa/1_mesele.md
    - 2-маселе: books/asay_musa/2_mesele.md
    - 3-маселе: books/asay_musa/3_mesele.md
    - 4-маселе: books/asay_musa/4_mesele.md
    - 5-маселе: books/asay_musa/5_mesele.md
    - 6-маселе: books/asay_musa/6_mesele.md
  - Кастамону лахикасы:
    - Кастамону лахикасы: books/kastamon/main.md
    - Унутчаактык: books/kastamon/content1.md
  - Лемалар:
    - Биринчи лема: books/lemalar/1_lema.md
  - Reference:
    - Abbreviations: reference/abbreviations.md
    - Admonitions: reference/admonitions.md
    - Buttons: reference/buttons.md
    - Code blocks: reference/code-blocks.md
    - Content tabs: reference/content-tabs.md
    - Data tables: reference/data-tables.md
    - Diagrams: reference/diagrams.md
    - Footnotes: reference/footnotes.md
    - Formatting: reference/formatting.md
    - Icons + Emojis: reference/icons-emojis.md
    - Images: reference/images.md
    - Lists: reference/lists.md
    - MathJax: reference/mathjax.md
    - Meta tags: reference/meta-tags.md
    - Variables: reference/variables.md
  - Insiders:
    - Sponsorship: insiders/index.md
    - Getting started:
      - Installation: insiders/getting-started.md
      - Changelog: insiders/changelog.md